### ISSUE TITLE
can you give us more details when we train it?

### ISSUE THREAD

**Issue by fresh382227905** [mathraim/ImageCaptioning#1]
what steps should we take?thanks

**Comment by mathraim** [comment]
Hello 
I am sorry I will put come comments there

**Comment by fresh382227905** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mathraim"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 凌晨5:54
收件人: "mathraim/ImageCaptioning"<ImageCaptioning@noreply.github.com&gt;; 
抄送: "LMF"<382227905@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mathraim/ImageCaptioning] can you give us more details when we train it? (#1)





 
Hello
 I am sorry I will put come comments there
